### ISSUE TITLE
Login on Home Page

### ISSUE THREAD

**Issue by soey** [ubilabs/diaspora#2]
As a user, I want to have the login form directly on the home page of the Pod, so that I can sign in directly without following another link.
- [ ] As a signed up user I can directly sign in from the home page

**Comment by KlausTrainer** [comment]
Laut @phaidros7 wurde das mittlerweile bereits über einen hinreichenden Workaround gelöst: "Login habe ich mittlerweile unaufwändig selber gelöst, indem ich ein 301 im Webserver mache".
